title: Blank Page
description: This place is not a place of honor... no highly esteemed deed is commemorated here... nothing valued is here.
tagline: Test
author:
  name: jph
  url: https;//www.jph.io/
social:
  name: jph
  links:
    - https://mstdn.social/@jph
    - https://twitter.com/jph7c1
